PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

inputs:
- name: gpbackup
  path: go/src/github.com/greenplum-db/gpbackup
- name: ccp_src
- name: cluster_env_files
- name: gppkgs

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    ccp_src/scripts/setup_ssh_to_cluster.sh

    cat <<SCRIPT > /tmp/run_tests.bash
      set -ex
      source env.sh

      # only install if not installed already
      is_installed_output=\$(source env.sh; gppkg -q gpbackup*gp*.gppkg)
      set +e
      echo \$is_installed_output | grep 'is installed'
      if [ \$? -ne 0 ] ; then
        set -e
        gppkg -i gpbackup*gp*.gppkg
      fi
      set -e
      cd \$GOPATH/src/github.com/greenplum-db/gpbackup
      export OLD_BACKUP_VERSION="$GPBACKUP_VERSION"

      make unit
      make integration
      make end_to_end
    SCRIPT

    out=`ssh -t mdw 'source env.sh && psql postgres -c "select version();"'`
    gpdbversion=`echo $out | sed -n 's/.*Greenplum Database \([0-9]\).*/\1/p'`
    mkdir /tmp/untarred
    tar -xzf gppkgs/gpbackup-gppkgs.tar.gz -C /tmp/untarred
    scp /tmp/untarred/gpbackup*gp$gpdbversion*.gppkg mdw:/home/gpadmin

    chmod +x /tmp/run_tests.bash
    scp /tmp/run_tests.bash mdw:/home/gpadmin/run_tests.bash
    ssh -t mdw "bash /home/gpadmin/run_tests.bash"
