PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

inputs:
- name: gpbackup
  path: go/src/github.com/greenplum-db/gpbackup
# - name: ccp_src
# - name: cluster_env_files
- name: gpdb_src
- name: sqldump
- name: bin_gpdb

outputs:
- name: artifacts

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    source gpdb_src/concourse/scripts/common.bash

    # setup cluster
    time install_and_configure_gpdb
    gpdb_src/concourse/scripts/setup_gpadmin_user.bash centos
    time make_cluster

    # setup environment
    source /usr/local/greenplum-db-devel/greenplum_path.sh
    source /opt/gcc_env.sh
    source gpdb_src/gpAux/gpdemo/gpdemo-env.sh
    sudo -u gpadmin go/src/github.com/greenplum-db/gpbackup/ci/scripts/generate_backup_artifact.bash

    # scp mdw:/tmp/regression_dump.sql.xz  artifacts/

    exit 1
    # combine gpbackup's separate tarballs for master and segments
    ssh -t sdw1 "pushd /tmp ; tar czvf backup_artifact.tar.gz backup_artifact ; popd"
    mkdir /tmp/gpbackup_allsegments
    scp mdw:/tmp/backup_artifact.tar.gz  /tmp/gpbackup_allsegments/gpbackup_mdw.tar.gz
    scp sdw1:/tmp/backup_artifact.tar.gz /tmp/gpbackup_allsegments/gpbackup_sdw1.tar.gz

    tar czvf artifacts/gpbackup_all.tar.gz -C /tmp/ gpbackup_allsegments

