PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

inputs:
- name: gpbackup
  path: go/src/github.com/greenplum-db/gpbackup
# - name: ccp_src
# - name: cluster_env_files
- name: gpdb_src
- name: sqldump
- name: bin_gpdb

outputs:
- name: artifacts

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    source gpdb_src/concourse/scripts/common.bash

    # setup cluster
    time install_and_configure_gpdb
    gpdb_src/concourse/scripts/setup_gpadmin_user.bash centos
    time make_cluster

    # setup environment
    source /usr/local/greenplum-db-devel/greenplum_path.sh
    source /opt/gcc_env.sh
    source gpdb_src/gpAux/gpdemo/gpdemo-env.sh

    xz -d ./sqldump/dump.sql.xz

    chown gpadmin:gpadmin -R $(pwd)/go

    sudo -u gpadmin go/src/github.com/greenplum-db/gpbackup/ci/scripts/generate_backup_artifact.bash

    cp /tmp/regression_dump.sql.xz  artifacts/.
    cp /tmp/backup_artifact.tar.gz artifacts/.

    tar czvf artifacts/gpbackup_regression_data.tar.gz -C artifacts/
