
PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

params:
  REQUIRES_DUMMY_SEC:

inputs:
- name: gpbackup
  path: go/src/github.com/greenplum-db/gpbackup
- name: ccp_src
- name: cluster_env_files
- name: dummy_seclabel
  optional: true
- name: gpbackup-dependencies

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    ccp_src/scripts/setup_ssh_to_cluster.sh

    cat <<SCRIPT > /tmp/setup_oracle_env.bash
    set -ex
        cat << ENV_SCRIPT > env.sh
        export GOPATH=/home/gpadmin/go
        source /usr/local/greenplum-db-devel/greenplum_path.sh
        export PGPORT=5432
        export MASTER_DATA_DIRECTORY=/data/gpdata/master/gpseg-1
        export PATH=\\\$GOPATH/bin:/usr/local/go/bin:\\\$PATH
    ENV_SCRIPT

    export GOPATH=/home/gpadmin/go
    chown gpadmin:gpadmin -R \$GOPATH
    chmod +x env.sh
    source env.sh

    gpconfig --skipvalidation -c fsync -v off
    gpstop -u
          
    if $REQUIRES_DUMMY_SEC ; then
      # dummy security label: copy library from bucket to correct location
      # (someday this will be part of the bin_gpdb tarball?)
      mkdir -p "\$GPHOME/postgresql"
      install -m 755 -T dummy_seclabel.so "\$GPHOME/lib/postgresql/dummy_seclabel.so"
      gpconfig -c shared_preload_libraries -v dummy_seclabel #--skipvalidation -c fsync -v off
      gpstop -ra
      gpconfig -s shared_preload_libraries | grep dummy_seclabel
    fi

    tar -zxf gpbackup-dependencies/dependencies.tar.gz -C \$GOPATH/src/github.com/greenplum-db/gpbackup/

    pushd \$GOPATH/src/github.com/greenplum-db/gpbackup
        make depend
        make build
    popd
    SCRIPT

    
    if $REQUIRES_DUMMY_SEC ; then
      scp dummy_seclabel/dummy_seclabel*.so mdw:/home/gpadmin/dummy_seclabel.so
    fi

    ssh -t clckwrk@mdw "sudo yum -y install wget git && wget https://storage.googleapis.com/golang/go1.10.3.linux-amd64.tar.gz && tar -xzf go1.10.3.linux-amd64.tar.gz && sudo mv go /usr/local"
    chmod +x /tmp/setup_oracle_env.bash
    rsync -a gpbackup-dependencies mdw:/home/gpadmin
    scp /tmp/setup_oracle_env.bash mdw:/home/gpadmin/setup_oracle_env.bash
    ssh -t mdw "mkdir -p /home/gpadmin/go/src/github.com/greenplum-db"
    scp -r go/src/github.com/greenplum-db/gpbackup mdw:/home/gpadmin/go/src/github.com/greenplum-db/gpbackup
    ssh -t mdw "bash /home/gpadmin/setup_oracle_env.bash"
