platform: linux

# image_resource:
#   type: docker-image
#   source:
#     repository: golang
#     tag: '1.10.3'
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '7-gcc6.2-llvm3.7'

inputs:
- name: gp_backup_manager_src
  path: go/src/github.com/pivotal/gp-backup-manager
- name: gpdb_src
- name: bin_gpdb
- name: gpbackup
- name: gpbackup-dependencies

run:
  path: bash
  args:
  - -c
  - |
    set -ex
    if [ ! -f bin_gpdb/bin_gpdb.tar.gz ] ; then
      mv bin_gpdb/*.tar.gz bin_gpdb/bin_gpdb.tar.gz
    fi


    source gpdb_src/concourse/scripts/common.bash
    time install_gpdb
    time ./gpdb_src/concourse/scripts/setup_gpadmin_user.bash
    time make_cluster

    source /usr/local/greenplum-db-devel/greenplum_path.sh

    ##### install latest version of golang
    git clone https://github.com/udhos/update-golang
    pushd update-golang
      sudo ./update-golang.sh
    popd
    #####

    # copy gpbackup & deps into the GOPATH used by user "gpadmin"
    export GOPATH=/home/gpadmin/go
    mkdir -p $GOPATH/src/github.com/greenplum-db
    cp -R gpbackup $GOPATH/src/github.com/greenplum-db/
    tar -zxf gpbackup-dependencies/dependencies.tar.gz -C $GOPATH/src/github.com/greenplum-db/gpbackup/
    mkdir -p $GOPATH/src/github.com/pivotal
    cp -R go/src/github.com/pivotal/gp-backup-manager $GOPATH/src/github.com/pivotal/

    chown -R gpadmin $GOPATH

    cat <<SCRIPT > /tmp/run_tests.bash
    #!/bin/bash
    set -ex
    cd ~
    source /usr/local/greenplum-db-devel/greenplum_path.sh

    # use "temp build dir" of parent shell
    source $(pwd)/gpdb_src/gpAux/gpdemo/gpdemo-env.sh
    export GOPATH=\$HOME/go
    # reference PATH defined by parent shell
    export PATH=/usr/local/go/bin:$PATH:\$PATH:\$GOPATH/bin
    go get github.com/alecthomas/gometalinter

    # Build gpbackup
    pushd \$GOPATH/src/github.com/pivotal/gp-backup-manager
      make depend
      make build
      make unit
      make integration
      make end_to_end
    popd

    SCRIPT

    chmod +x /tmp/run_tests.bash
    su - gpadmin bash -c /tmp/run_tests.bash
